---
title: "Lab 5 Analysis"
author: "Stephen Cook"
date: "Oct 27 2018"
output:
  pdf_document: default
---

## Import packages


```{r, message=FALSE}
require(tidyverse)
require(broom)
```


## Import data


```{r}
climate <- read.csv(file = "climate_data.csv", header = T, sep = ",")
```

## Will future near-surface air temperature be influence by GHG emissions?

```{r}
july <- climate %>%
  filter(MONTH == 7) %>%
  filter(LATITUDE == 46)
```

```{r}
july_plot <- ggplot() +
  geom_point(data = july,
             aes(x = YEAR, y = TEMPERATURE,
                 colour = SCENARIO)) +
  stat_smooth(data = july,
              aes(x = YEAR, y = TEMPERATURE, colour = SCENARIO),
              method = "lm")

july_plot
```

```{r}
july_model <- lm(data = july,
                 TEMPERATURE ~ YEAR*SCENARIO)

summary(july_model)
```

```{r}
july <- climate %>%
  filter(MONTH == 7) %>%
  filter(LATITUDE == 46) %>%
  filter(SCENARIO == "A2")

july_a2_model <- lm(data = july,
                    TEMPERATURE ~ YEAR)

summary(july_a2_model)
```


# For objective 3

Using just the January temperatures and the A2 scenario, great a graph and model the effects of latitude (x-axis values) on mean tempreature change (y-axis values). We will go over the code in class. 

```{r}
lat_question <- climate %>%
  filter(MONTH == 1) %>%
  filter(SCENARIO == "A2") 
```

```{r}
lat_slopes <- lat_question %>%
  group_by(LATITUDE) %>%
  do(data.frame(tidy(lm(TEMPERATURE ~ YEAR, data = .)))) %>%
  select(LATITUDE, term, estimate) %>%
  filter(term == "YEAR") %>%
  mutate(century_change = estimate*100)
  
```

