---
title: "Lab 3 Analysis"
author: "Stephen Cook"
date: "Oct 6 2018"
output:
  word_document: default
  pdf_document: default
---

## Import packages


```{r, message=FALSE}
require(tidyverse)
require(lubridate)
```


## Import data


```{r}
lww <- read.csv(file = "lww_fall_18.csv", header = T, sep = ",")
```

## Calculations

Is management activity influencing the *abundance* of cattail?

```{r}
management_abundance <- lww %>%
  select(CELL, CAT_PRESENT) %>%
  group_by(CELL) %>%
  summarise(CAT_PRESENT = sum(CAT_PRESENT)) %>%
  mutate(CAT_ABSENT = 50 - CAT_PRESENT)


managment.abund <- chisq.test(management_abundance, simulate.p.value = TRUE)
managment.abund
```

Is management activity influencing the *dominance* of cattail?

```{r}
management_dominance <- lww %>%
  select(CELL, CAT_DOMINANT) %>%
  group_by(CELL) %>%
  summarise(CAT_DOMINANT = sum(CAT_DOMINANT)) %>%
  mutate(CAT_NOT_DOM = 50 - CAT_DOMINANT)

managment.dom <- chisq.test(management_dominance, simulate.p.value = TRUE)
managment.dom
```

Is management activity influencing species richness?

```{r}
cell1_richness <- lww %>%
  select(CELL, RICHNESS) %>%
  filter(CELL == 1)

cell2_richness <- lww %>%
  select(CELL, RICHNESS) %>%
  filter(CELL == 2)

richness.test <- t.test(cell1_richness$RICHNESS, cell2_richness$RICHNESS)

richness.test
```

















```{r}
manag.rich <- lww %>%
  select(CELL, RICHNESS) %>%
  mutate(RICH_CATEGORY = ifelse(RICHNESS > 4, 1, 0)) %>%
  select(-RICHNESS)
```

















Does typha dominance influence species richness?

```{r}
typha_dom_richness <- lww %>%
  select(CAT_DOMINANT, RICHNESS) %>%
  filter(CAT_DOMINANT == 1)

other_dom_richness <- lww %>%
  select(CAT_DOMINANT, RICHNESS) %>%
  filter(CAT_DOMINANT == 0)

typha.test <- t.test(typha_dom_richness$RICHNESS, other_dom_richness$RICHNESS)

typha.test
```

```{r}
manag.dom <- lww %>%
  select(CAT_DOMINANT, RICHNESS) %>%
  mutate(RICH_CATEGORY = ifelse(RICHNESS > 4, 1, 0)) %>%
  select(-RICHNESS) %>%
  group_by(CAT_DOMINANT) %>%
  summarise(RICH_HIGH = sum(RICH_CATEGORY)) %>%
  mutate(RICH_LOW = ifelse(CAT_DOMINANT == 1, 76-RICH_HIGH, 24-RICH_HIGH))


new.test <- chisq.test(manag.dom, simulate.p.value = TRUE)
new.test
```







```{r}
test <- lww %>%
  select(CAT_DOMINANT, RICHNESS)



sum(test$CAT_DOMINANT)
```



```{r}
typha_richness <- lww %>%
  select(CAT_DOMINANT, RICHNESS) %>%
  filter(CAT_DOMINANT == 1)

other_richness <- lww %>%
  select(CAT_DOMINANT, RICHNESS) %>%
  filter(CAT_DOMINANT == 0)


richness.test <- t.test(typha_richness$RICHNESS, other_richness$RICHNESS)

richness.test
```












