---
output:
  pdf_document: default
  html_document: default
---
# Nutrient limitation


## Background information

All organisms need nutrients to grow and reproduce. For primary producers, nitrogen (N) and phosphorus (P) are two macronutrients that frequently limit growth (or are in . The primary source of inorganic P is from P-bearing rock, or from the remineralization of P from organic sources (i.e. the decomposition of dead biomass). N, on the other hand, composes nearly 78% of the atmosphere, but this inorganic N-pool is largely inaccessible to most organisms. Some organisms are able to fix N (N-fixing organisms) and access this gaseous pool, which gives them a competitive advantage when N is low in the environment. 



## Objectives

We collected macroinvertebrates from 2 sites in central Texas that differed in anthropogenic impact using 1 m^2^ kick-screens. Neils Creek is a relatively unimpacted site, with some pasture, farmland, and forrest in its watershed, while Harris Creek is surrounded by heavy farming activity and neighborhoods. Actually, the Fall 2017 class collected the Harris Creek data for you, but you get the idea. You will use this data to answer the following questions:

1. Does anthropogenic impact influence biodiversity?
    * Assess this question by calculating alpha, gamma, and beta-diversity for the 2 sites.

2. Does anthropogenic impact influence the EPT taxa in a stream?
    * Assess this question by calculating the %EPT in each sample. 
    

## Lab report specifics

1. Introduction
    * Why is biodiversity important?
    * How is biodiversity measured?
    * Why are macroinvertebrates useful?
    * Objectives
    * Hypotheses
2. Methods
    * Experimental design and field work
    * laboratory work
    * Calculations / statistics
3. Results
    * Question 1 (text **AND** graph)
    * Question 2 (text **AND** graph)
4. Discussion
    * Hypotheses rejected/supported
    * Provide a coherent explanation/interpretation of your results
